name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 24, 25-ea ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Cache Maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v4
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
      - name: Build ${{ matrix.java-version }}
        run: mvn -B clean test

      - name: id modified classes
        id: modified
        run: |
         git fetch origin master:master || true
         files=$(git diff --name-only origin/master...HEAD -- src/main/java || true)
          
         if [ -z "$files" ]; then
          echo "No files changes"
          echo "pattern=" >> $GITHUB_OUTPUT
          exit 0
         fi
         pattern=$(echo "$files" | \
           sed -n 's|^src/main/java/||p' | \
           sed -E 's|\.java$|.*|' | \
           sed 's|/|.|g' | \
           sort -u | paste -sd, -)
          
         if [ -z "$pattern" ]; then
          echo "pattern=" >> $GITHUB_OUTPUT
          else
           echo "pattern=$pattern" >> $GITHUB_OUTPUT
         fi

      - name: pitest report
        if: ${{ steps.changed.outputs.pattern != '' }}
        run: |
          PATTERN="${{ steps.changed.outputs.pattern }}"
          echo "Running PIT on: $PATTERN"
          mvn org.pitest:pitest-maven:mutationCoverage -DtargetClasses="$PATTERN"

      - name: id mutation score
        id : new
        run: |
          FILE=$(ls -d target/pit-reports/*/index.html 2>/dev/null | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "Could not find PIT report index.html under target/pit-reports/*"
            exit 1
          fi
          SCORE=$(grep -oP '(?<=td>)[0-9.]+' "$FILE" | sed -n '3p')
          if [ -z "$SCORE" ]; then
            echo "Could not parse mutation score from $FILE"
            exit 1
          fi
          echo "Found score: $SCORE" 
          echo "score=$SCORE" >> $GITHUB_OUTPUT
        # Théoriquement, le score de mutation détecté est maintenant disponible pour le prochain step

      - name: Find old score
        id: old
        run: |
          FILE=$(ls -d .github/metrics/mutation-score.txt 2>/dev/null | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "Could not find PIT report index.html under target/pit-reports/*"
            exit 1
          fi
          OLDSCORE=$(grep -oP '\b([0-9]{1,2}|100)\b' "$FILE" | head -n1)
          if [ -z "$SCORE" ]; then
            echo "Could not parse mutation score from $FILE"
            exit 1
          fi
            echo "Found old score: $OLDSCORE" 
            echo "oldscore=$OLDSCORE" >> $GITHUB_OUTPUT

      - name: Compare scores
        run: |
          NEW="${{ steps.new.outputs.score }}"
          OLD="${{ steps.old.outputs.oldscore }}"

          if (( $(echo "$NEW < $OLD" | bc -l) )); then
            echo "Mutation score dropped"
            exit 1
          else
            echo "Mutation score is at least the same"
          fi

      - name: Update old score
        if: success()
        run: |
          echo "${{ steps.new.outputs.score }}" > .github/metrics/mutation-score.txt

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .github/metrics/mutation-score.txt
          git commit -m "Update mutation score baseline" "" exit 0
          git push
